---

- console:
    enable: on

- epics:
    enable: on
    # $HOSTNAME: machine hostname
    prefix: "BEAST:$hostname:SENS:"
    fpgatype: "artix7"

- http:
    enable: on
    url: "http://192.168.20.1:8186/write"
    username: "monitor"
    password: "fpga4all"
